### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [yzgd/fastSHT#1]
I suggest adding topics such as `sht`, `spherical-harmonics`, `sky-map`, `astronomy` in the About section at https://github.com/liuhao-cn/fastSHT.

**Comment by liuhao-cn** [comment]
Dear Beliavsky,Thank you for your message! Some of your suggested contents can be found in https://arxiv.org/abs/2208.10154, which is attched to the introduction section of the repository. We shall also consider adding more such introductions directly to github later on.BestHaoHao Liu-------- 原始邮件 --------发件人： Beliavsky ***@***.***>日期： 2022年8月26日周五 21:01收件人： liuhao-cn/fastSHT ***@***.***>抄送： Subscribed ***@***.***>主    题： [liuhao-cn/fastSHT] add topics (Issue #1)
I suggest adding topics such as sht, spherical-harmonics, sky-map, astronomy in the About section at https://github.com/liuhao-cn/fastSHT.
